title: Statistical Learning Quizzes
author: Jana Bormann
copyright: "2025"

# Reference: https://jupyterbook.org/en/stable/customize/config.html

# Do not execute notebooks
execute:
  execute_notebooks: "auto"
  timeout: 500
  exclude_patterns: ["*/Exercises.ipynb", "*solutions*.ipynb"]


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/pmus-lab/module-quizzes
  branch: main

# Add GitHub buttons to your book
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  baseurl: https://pmus-lab.github.io/module-quizzes
  
sphinx:
  html_context:
    default_mode: dark
  recursive_update: true
  extra_css:
    - _static/custom.css
  extra_javascript:
    - _static/custom.js
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]

    # Tell myst-nb to actually keep/render Plotly's MIME bundle
    nb_mime_priority_overrides:
      - [html, application/vnd.plotly.v1+json, 0]
    
# Google colab launch button
launch_buttons:
  colab_url: "https://colab.research.google.com"
  